services:
  server:
    container_name: server
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - .:/var/log
    networks:
      - server-network
    depends_on:
      - redis
      - mongo
    
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - server-network
    
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - server-network
    
networks:
  server-network: